# Site settings
title: "HeroCraft: Ascendant's Path"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  HeroCraft: Ascendant's Path is a fantasy board game for 2-6 players. Designed by Andrew Maul.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.herocraftgame.com" # the base hostname & protocol for your site

#Development
lorem: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ac ex euismod, maximus quam id, pellentesque purus. Fusce eget mauris diam. Suspendisse hendrerit nec tellus sit amet tempor. Mauris quis elit ac velit elementum vestibulum. Curabitur dui nisi, sagittis sed luctus cursus, ultricies nec neque. Ut nibh orci, vestibulum at convallis nec, malesuada vitae leo. Sed gravida erat commodo neque malesuada, vel semper sapien placerat. Sed egestas auctor ante, eget porttitor tortor dictum non. Aenean faucibus augue non tempor dapibus."

# Build settings
markdown: kramdown
